### ISSUE TITLE
"You're viewing older messages" bar at the bottom doesn't pop out

### ISSUE THREAD

**Issue by mi1kk** [devinkid1/Pop#2]
The text and generated shadow does pop out, but the UI element doesn't, is this something that was overlooked or simply doesn't work?
![image](https://user-images.githubusercontent.com/86815436/127748419-2a237842-087d-4971-9b60-aab33cdc453a.png)

**Comment by devinkid1** [comment]
I remember seeing that and forgetting about it, ill try to fix it thank you

**Comment by devinkid1** [comment]
Should be fixed now, hopefully
